/**
 * routes/cockpit.ts — Founder Cockpit Express 路由 (D220-PHASE3)
 *
 * 将 D220 仪表盘从独立 Python HTTP 服务器集成到主 Express 服务器。
 * 同源访问，Codex 内嵌浏览器可直接加载。
 *
 * GET /cockpit        — 返回完整仪表盘 HTML
 * GET /api/cockpit/data — 返回 JSON 数据（5 分钟轮询）
 *
 * 注意：scripts/control-tower/ 含连字符，不能直接用 Python import。
 * 使用 spec_from_file_location 按文件路径加载模块。
 *
 * 契约:
 *   @input  — 无（GET 请求）
 *   @output — HTML / JSON
 *   @degraded — Python 脚本不可用 → 500 + degraded:true
 */
import { Router, type Request, type Response } from 'express';
import { execSync } from 'child_process';
import { join } from 'path';
import { writeFileSync, unlinkSync, mkdtempSync } from 'fs';
import { createLogger } from '@synova/logger';

const log = createLogger('routes/cockpit');
const router = Router();

const SCRIPT_PATH = join(process.cwd(), 'scripts/control-tower/generate-dashboard.py');
const PYTHON = 'python3';

/**
 * Build and run a Python runner script via temp file.
 * Uses spec_from_file_location to load the module (bypasses hyphens in dir name).
 * Sets PYTHONIOENCODING=utf-8 to ensure Chinese characters survive Windows GBK.
 */
function execPython(scriptBody: string): string {
  const tmpDir = mkdtempSync(join(process.cwd(), '.cockpit-tmp-'));
  const runner = join(tmpDir, '_runner.py');
  try {
    const runnerCode = [
      '# auto-generated by cockpit.ts',
      'import sys, json, importlib.util',
      `spec = importlib.util.spec_from_file_location('gd', ${JSON.stringify(SCRIPT_PATH)})`,
      'mod = importlib.util.module_from_spec(spec)',
      'spec.loader.exec_module(mod)',
      scriptBody,
    ].join('\n');
    writeFileSync(runner, runnerCode, 'utf-8');
    return execSync(`${PYTHON} "${runner}"`, {
      encoding: 'utf-8',
      timeout: 30000,
      cwd: process.cwd(),
      env: { ...process.env, PYTHONIOENCODING: 'utf-8' },
    }).trim();
  } finally {
    try { unlinkSync(runner); } catch { /* ignore */ }
    try { unlinkSync(tmpDir); } catch { /* ignore */ }
  }
}

// GET /favicon.ico — 1×1 透明图标（避免 404）
router.get('/favicon.ico', (_req: Request, res: Response) => {
  res.setHeader('Content-Type', 'image/x-icon');
  res.status(204).end();
});

// GET /cockpit — 完整仪表盘 HTML
router.get('/cockpit', (_req: Request, res: Response) => {
  try {
    const html = execPython(
      'data = mod.collect_dashboard_data()\nprint(mod.render_html(data))',
    );
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.send(html);
  } catch (err) {
    log.warn({ err }, 'Dashboard HTML generation failed');
    res.status(500).json({ ok: false, error: 'Dashboard unavailable', degraded: true });
  }
});

// GET /api/cockpit/data — JSON 数据端点（5 分钟轮询）
router.get('/api/cockpit/data', (_req: Request, res: Response) => {
  try {
    const result = execPython(
      'data = mod.collect_dashboard_data()\nprint(json.dumps(data, default=str))',
    );
    res.json(JSON.parse(result));
  } catch (err) {
    log.warn({ err }, 'Dashboard data collection failed');
    res.status(500).json({ ok: false, error: 'Data unavailable', degraded: true });
  }
});

export default router;
