/**
 * @synova/ontology — Edge Type Constants
 *
 * 42 edge type string constants from extensions/ontology/edge-types/ JSON Schema.
 * I2-Phase2: 7 KEEP + 4 MODIFY-rename + 2 @deprecated (DEPLOYS/FUNDS) + 38 NEW = 51
 * (55 JSON files - 4 renamed MODIFY old names = 51 EdgeType entries)
 * Replaces old SOGEdgeType enum. DO NOT add backward-compatible aliases.
 *
 * KEEP (7): SIGNAL_TRANSMITS, INCENTIVE_BINDS, DECISION_CONCENTRATES, LOCKS_IN,
 *           CONSTRAINS, CUMULATIVE_LEARNING, BRAND_BUILDS
 * MODIFY-rename (4): OPERATIONAL_EXECUTION (was PRODUCES),
 *           ASSUMPTION_TRIGGERED_REALLOCATION (was EXTERNAL_ASSUMPTION_BINDS),
 *           TECH_INFRASTRUCTURE (was AUGMENTS),
 *           CROSS_FUNCTIONAL_SYNERGY (was COUPLES)
 * @deprecated (2): DEPLOYS, FUNDS — kept for Phase 4 migration
 * NEW (29): from 42-pure-edge list Phase 1 JSON Schema
 *
 * Source of truth: extensions/ontology/edge-types/
 *
 * @module @synova/ontology/edge-types
 */

export const EdgeType = {
  // ── KEEP (7) — unchanged from old system ──
  SIGNAL_TRANSMITS: 'SIGNAL_TRANSMITS',
  INCENTIVE_BINDS: 'INCENTIVE_BINDS',
  DECISION_CONCENTRATES: 'DECISION_CONCENTRATES',
  LOCKS_IN: 'LOCKS_IN',
  CONSTRAINS: 'CONSTRAINS',
  CUMULATIVE_LEARNING: 'CUMULATIVE_LEARNING',
  BRAND_BUILDS: 'BRAND_BUILDS',

  // ── MODIFY-renamed (4) — old edges renamed to 42-edge names ──
  OPERATIONAL_EXECUTION: 'OPERATIONAL_EXECUTION',
  ASSUMPTION_TRIGGERED_REALLOCATION: 'ASSUMPTION_TRIGGERED_REALLOCATION',
  TECH_INFRASTRUCTURE: 'TECH_INFRASTRUCTURE',
  CROSS_FUNCTIONAL_SYNERGY: 'CROSS_FUNCTIONAL_SYNERGY',

  // ── @deprecated (2) — kept for Phase 4 migration ──
  /** @deprecated Use TALENT_ACQUISITION/TALENT_DEPLOYMENT/EQUIPMENT_ACQUISITION — kept for Phase 4 migration */
  DEPLOYS: 'DEPLOYS',
  /** @deprecated Use CAPITAL_ACQUISITION/CAPITAL_ALLOCATION — kept for Phase 4 migration */
  FUNDS: 'FUNDS',

  // ── NEW (38) — 42-edge JSON minus 4 MODIFY-renamed ──
  ENVIRONMENTAL_SCAN: 'ENVIRONMENTAL_SCAN',
  SIGNAL_UPWARD_PASS: 'SIGNAL_UPWARD_PASS',
  EXTERNAL_FEEDBACK: 'EXTERNAL_FEEDBACK',
  SENSING_CALIBRATION: 'SENSING_CALIBRATION',

  CAPITAL_ACQUISITION: 'CAPITAL_ACQUISITION',
  CAPITAL_SOURCE_MIX: 'CAPITAL_SOURCE_MIX',
  TALENT_ACQUISITION: 'TALENT_ACQUISITION',
  TALENT_FILTER: 'TALENT_FILTER',
  DATA_COLLECTION: 'DATA_COLLECTION',
  EQUIPMENT_ACQUISITION: 'EQUIPMENT_ACQUISITION',

  REPUTATION_ATTRACTION: 'REPUTATION_ATTRACTION',
  EFFICIENCY_ATTRACTION: 'EFFICIENCY_ATTRACTION',
  CAPITAL_ALLOCATION: 'CAPITAL_ALLOCATION',
  DECISION_AUTHORITY: 'DECISION_AUTHORITY',
  TALENT_DEPLOYMENT: 'TALENT_DEPLOYMENT',
  INFORMATION_FLOW: 'INFORMATION_FLOW',
  INCENTIVE_ALIGNMENT: 'INCENTIVE_ALIGNMENT',

  RULE_CONSTRAINT: 'RULE_CONSTRAINT',
  ORGANIZATIONAL_LEARNING: 'ORGANIZATIONAL_LEARNING',
  KNOWLEDGE_SHARING: 'KNOWLEDGE_SHARING',
  TRUST_FRICTION_REDUCTION: 'TRUST_FRICTION_REDUCTION',
  ROUTINE_RIGIDITY: 'ROUTINE_RIGIDITY',

  INNOVATION_OUTPUT: 'INNOVATION_OUTPUT',
  BRAND_BUILDING: 'BRAND_BUILDING',
  DEMAND_TO_SPEC: 'DEMAND_TO_SPEC',
  SERVICE_SUPPORT: 'SERVICE_SUPPORT',

  VALUE_PRICING: 'VALUE_PRICING',
  CUSTOMER_LOCKIN: 'CUSTOMER_LOCKIN',
  CHANNEL_DELIVERY: 'CHANNEL_DELIVERY',
  COMPETITIVE_POSITIONING: 'COMPETITIVE_POSITIONING',
  PROCUREMENT_BARGAINING: 'PROCUREMENT_BARGAINING',
  CUSTOMER_DATA_LOOP: 'CUSTOMER_DATA_LOOP',
  MARKET_SHARE_CAPTURE: 'MARKET_SHARE_CAPTURE',

  PROFIT_REINVESTMENT: 'PROFIT_REINVESTMENT',
  TALENT_RETENTION: 'TALENT_RETENTION',
  KNOWLEDGE_REUSE: 'KNOWLEDGE_REUSE',
  REPUTATION_FLYWHEEL: 'REPUTATION_FLYWHEEL',
  RETENTION_PROTECTS_KNOWLEDGE: 'RETENTION_PROTECTS_KNOWLEDGE',
} as const;

/** Union type of all 51 edge type string values */
export type EdgeType = typeof EdgeType[keyof typeof EdgeType];

/** All 51 edge types in a flat array */
export const ALL_EDGE_TYPES: readonly EdgeType[] = [
  // KEEP (7)
  EdgeType.SIGNAL_TRANSMITS,
  EdgeType.INCENTIVE_BINDS,
  EdgeType.DECISION_CONCENTRATES,
  EdgeType.LOCKS_IN,
  EdgeType.CONSTRAINS,
  EdgeType.CUMULATIVE_LEARNING,
  EdgeType.BRAND_BUILDS,

  // MODIFY-renamed (4)
  EdgeType.OPERATIONAL_EXECUTION,
  EdgeType.ASSUMPTION_TRIGGERED_REALLOCATION,
  EdgeType.TECH_INFRASTRUCTURE,
  EdgeType.CROSS_FUNCTIONAL_SYNERGY,

  // @deprecated (2)
  EdgeType.DEPLOYS,
  EdgeType.FUNDS,

  // NEW (29)
  EdgeType.ENVIRONMENTAL_SCAN,
  EdgeType.SIGNAL_UPWARD_PASS,
  EdgeType.EXTERNAL_FEEDBACK,
  EdgeType.SENSING_CALIBRATION,
  EdgeType.CAPITAL_ACQUISITION,
  EdgeType.CAPITAL_SOURCE_MIX,
  EdgeType.TALENT_ACQUISITION,
  EdgeType.TALENT_FILTER,
  EdgeType.DATA_COLLECTION,
  EdgeType.EQUIPMENT_ACQUISITION,
  EdgeType.REPUTATION_ATTRACTION,
  EdgeType.EFFICIENCY_ATTRACTION,
  EdgeType.CAPITAL_ALLOCATION,
  EdgeType.DECISION_AUTHORITY,
  EdgeType.TALENT_DEPLOYMENT,
  EdgeType.INFORMATION_FLOW,
  EdgeType.INCENTIVE_ALIGNMENT,
  EdgeType.RULE_CONSTRAINT,
  EdgeType.ORGANIZATIONAL_LEARNING,
  EdgeType.KNOWLEDGE_SHARING,
  EdgeType.TRUST_FRICTION_REDUCTION,
  EdgeType.ROUTINE_RIGIDITY,
  EdgeType.INNOVATION_OUTPUT,
  EdgeType.BRAND_BUILDING,
  EdgeType.DEMAND_TO_SPEC,
  EdgeType.SERVICE_SUPPORT,
  EdgeType.VALUE_PRICING,
  EdgeType.CUSTOMER_LOCKIN,
  EdgeType.CHANNEL_DELIVERY,
  EdgeType.COMPETITIVE_POSITIONING,
  EdgeType.PROCUREMENT_BARGAINING,
  EdgeType.CUSTOMER_DATA_LOOP,
  EdgeType.MARKET_SHARE_CAPTURE,
  EdgeType.PROFIT_REINVESTMENT,
  EdgeType.TALENT_RETENTION,
  EdgeType.KNOWLEDGE_REUSE,
  EdgeType.REPUTATION_FLYWHEEL,
  EdgeType.RETENTION_PROTECTS_KNOWLEDGE,
] as const;
