#!/usr/bin/env python3
"""
gen-task-board.py — 仪表盘 git 化生成器 v1 (D320)

一句话: 把 DASHBOARD-CN.md / DASHBOARD.md 从"Codex 手工维护"变成
"git 状态 + 文件事实 + 薄手动层"的渲染产物。

权威文档: SYNOVA-IMPL-D320-仪表盘git化生成器-20260808.md
  + D296 数据真实性 (缺失/过期 -> 视图 degraded, 禁止假 0/假绿)
  + D220 生成器契约 (generate-dashboard.py 数据采集骨架)

契约:
  @input  — git log 全历史 D# 提交 + dev docs 头部注释 + .claude/task-briefs/
            + .codex/control-tower/VERSION.md + version.log + gh run list
            + .codex/audit/audit-result.json + docs/synova/coverage/board-override.yaml
            + 现有 DASHBOARD 手动区 (MANUAL marker 内)
  @output — docs/synova/DASHBOARD-CN.md + DASHBOARD.md (Markdown 任务看板)
            AUTO marker 内 git 派生 (禁止手写); MANUAL marker 内原样保留
  @degraded — 数据源缺失/失败 -> 视图内逐项诚实标注, 绝不伪造数字

幂等: 自动区无变化 -> 不写文件 (mtime 不变, 防每次提交噪音)。
首次运行: 无 marker 的旧文件整体迁入 MANUAL 区 (仅剥旧 frontmatter + 首标题),
此后 MANUAL 区逐字节保留, 生成器绝不修改 marker 之间内容。

用法:
  python gen-task-board.py              # 生成 CN + EN 两份
  python gen-task-board.py --lang cn    # 仅 CN
  python gen-task-board.py --dry-run    # 只计算不写文件
  python gen-task-board.py --help
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set, Tuple

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

PROJECT_ROOT = Path(__file__).parent.parent.parent

# ─── marker 契约 (dev doc §3.2) ──────────────────────────────────────────────
AUTO_START = "<!-- AUTO:START -->"
AUTO_END = "<!-- AUTO:END -->"
MANUAL_START = "<!-- MANUAL:START -->"
MANUAL_END = "<!-- MANUAL:END -->"

# 主开发分支 (双机规划 2026-08-08)
DEFAULT_BRANCH = "feat/prompt-architecture"

# gh run list 默认拉取量
CI_LIMIT = 10

# ─── 语言文案 ─────────────────────────────────────────────────────────────────
L10N: Dict[str, Dict[str, str]] = {
    "cn": {
        "file_title": "Synova 项目仪表盘",
        "frontmatter_status": "由 scripts/control-tower/gen-task-board.py 生成 — 自动区为 git 派生事实",
        "notice": (
            "> 本文件由 `scripts/control-tower/gen-task-board.py` 生成。\n"
            "> **自动区**（AUTO marker 内）为 git/文件事实派生，禁止手写；\n"
            "> **手动区**（MANUAL marker 内）人工维护，生成器原样保留。\n"
            "> 人工修改任务事实 → 编辑 `docs/synova/coverage/board-override.yaml` 或手动区。"
        ),
        "task_status": "## 任务状态（git 派生）",
        "task_note": "> 数据源: git log 全历史 D# + dev docs 头 + task briefs + board-override.yaml。逐项缺失 → degraded 标注。",
        "audit_note": "审计（audit-result.json）",
        "version_hist": "## 版本历史",
        "version_note": "数据源: VERSION.md + version.log + git tag（D319 后增强）。",
        "ci_status": "## CI 状态（gh run）",
        "sync_health": "## 同步健康（D323 预留）",
        "empty_table": "（空 — 仓库无 D# 相关提交/文档）",
        "empty_version": "（空 — VERSION.md 缺失或不可解析）",
        "empty_run": "（无 gh run 数据）",
        "unknown": "未知",
        "task": "任务",
        "status": "状态",
        "commit": "提交",
        "author": "作者",
        "date": "日期",
        "pushed": "推送",
        "ci": "CI",
        "audit": "审计",
        "pushed_yes": "✅",
        "pushed_no": "❌",
        "version": "版本",
        "version_date": "日期/时间",
        "changes": "变更",
        "tag": "git tag",
        "run": "Run",
        "workflow": "工作流",
        "run_status": "状态",
        "conclusion": "结论",
        "related_d": "关联 D#",
        "unpushed": "未推送提交",
        "porcelain": "工作区变更",
        "sync_reserved": "D323 填充: 双机同步健康完整视图。",
        "state_committed": "✅ 已提交",
        "state_brief": "📝 brief",
        "state_todo": "待办",
        "tag_pending": "版本待 tag（D319 后增强）",
    },
    "en": {
        "file_title": "Synova Project Dashboard",
        "frontmatter_status": "Generated by scripts/control-tower/gen-task-board.py — auto zone is git-derived fact",
        "notice": (
            "> This file is generated by `scripts/control-tower/gen-task-board.py`.\n"
            "> **Auto zone** (inside AUTO markers) is git/file-derived fact — do not hand-edit.\n"
            "> **Manual zone** (inside MANUAL markers) is human-maintained — the generator preserves it verbatim.\n"
            "> To change task facts by hand: edit `docs/synova/coverage/board-override.yaml` or the manual zone."
        ),
        "task_status": "## Task Status (git-derived)",
        "task_note": "> Sources: full-history git log (D#) + dev-doc headers + task briefs + board-override.yaml. Missing sources are marked degraded per item.",
        "audit_note": "Audit (audit-result.json)",
        "version_hist": "## Version History",
        "version_note": "Sources: VERSION.md + version.log + git tag (enhanced after D319).",
        "ci_status": "## CI Status (gh run)",
        "sync_health": "## Sync Health (reserved — D323)",
        "empty_table": "(empty — no D# commits/docs in this repository)",
        "empty_version": "(empty — VERSION.md missing or unparseable)",
        "empty_run": "(no gh run data)",
        "unknown": "unknown",
        "task": "Task",
        "status": "Status",
        "commit": "Commit",
        "author": "Author",
        "date": "Date",
        "pushed": "Pushed",
        "ci": "CI",
        "audit": "Audit",
        "pushed_yes": "✅",
        "pushed_no": "❌",
        "version": "Version",
        "version_date": "Date/Time",
        "changes": "Changes",
        "tag": "git tag",
        "run": "Run",
        "workflow": "Workflow",
        "run_status": "Status",
        "conclusion": "Conclusion",
        "related_d": "Related D#",
        "unpushed": "Unpushed commits",
        "porcelain": "Working-tree changes",
        "sync_reserved": "D323 will fill: full two-machine sync-health view.",
        "state_committed": "✅ committed",
        "state_brief": "📝 brief",
        "state_todo": "todo",
        "tag_pending": "version tag pending (D319 enhancement)",
    },
}

# ─── 契约: 各数据源解析 (失败 -> 返回空 + 调用方 degraded 标注, 不抛异常) ──────

def run_git(root: Path, args: List[str], timeout: int = 20) -> Optional[str]:
    """执行 git 命令, 返回 stdout (去尾部空白); 失败/超时返回 None。

    @input  — root: 仓库目录; args: git 参数 (不含 'git')
    @output — stdout 文本 | None
    @degraded — 非零退出/OSError/超时 -> None (调用方标注 degraded)
    """
    try:
        r = subprocess.run(
            ["git", "-C", str(root), *args],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=timeout,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if r.returncode != 0:
        return None
    return r.stdout


# %x1f 作字段分隔 — 提交 subject 可能含 '|', 不能用 '|' 分隔
_GIT_LOG_FMT = "%H%x1f%an%x1f%ae%x1f%ad%x1f%s"


# ─── 品牌迁移显示层归一 (2026-08-14) ─────────────────────────────────────────
# 旧项目代号 ClawOrg → Synova。仅归一仪表盘显示，不改写 git 历史：
# git log 的原始 author 保持 ClawOrg（历史事实），本映射只影响 render 出来的
# 作者列。显式声明、可审计，杜绝"仪表盘 vs git log 不一致"被误判为假数据。
AUTHOR_BRAND_MAP: Dict[str, str] = {
    "ClawOrg-Win": "Synova-Win",
    "ClawOrg-Mac": "Synova-Mac",
    "ClawOrg": "Synova",
    "哇呢": "Synova-Mac",
}
EMAIL_BRAND_MAP: Dict[str, str] = {
    "claworg@users.noreply.github.com": "synova@users.noreply.github.com",
    "wane@wanedeMacBook-Pro.local": "synova@users.noreply.github.com",
}


def normalize_author(author: str) -> str:
    """author 显示名归一 (品牌迁移 ClawOrg → Synova)。未命中则原样返回。"""
    return AUTHOR_BRAND_MAP.get(author, author)


def normalize_email(email: str) -> str:
    """email 显示名归一 (品牌迁移)。未命中则原样返回。"""
    return EMAIL_BRAND_MAP.get(email, email)


def git_log_d(root: Path) -> List[Dict[str, Any]]:
    """全历史 D# 提交 (git log --grep=D[0-9], BRE): 最新在前。

    @input  — root: 仓库目录
    @output — [{hash, short_hash, author, email, date, subject, d_ids}]
    @degraded — git 失败 -> [] (无 D# 行); 空仓库 -> []
    """
    out = run_git(root, ["log", "--grep=D[0-9]", "--format=" + _GIT_LOG_FMT, "--date=short"])
    if out is None:
        return []
    rows: List[Dict[str, Any]] = []
    for line in out.splitlines():
        parts = line.split("\x1f")
        if len(parts) < 5:
            continue
        h, author, email, date, subject = parts[0], parts[1], parts[2], parts[3], parts[4]
        d_ids = re.findall(r"D\d+", subject)
        if not d_ids:
            continue
        # 任务归属 = 首个 D#（conventional commit scope, 如 "chore(D316): ..."）。
        # 后置 D# 仅为提及（如 "…固化 D313-D316 协作教训"）— 不参与归属。
        d_ids = [d_ids[0]]
        rows.append({
            "hash": h, "short_hash": h[:7],
            "author": normalize_author(author), "email": normalize_email(email),
            "date": date, "subject": subject, "d_ids": d_ids,
        })
    return rows


def git_unpushed(root: Path, branch: str) -> Optional[Set[str]]:
    """origin/<branch>..HEAD 的未推送提交哈希集合。

    @input  — root: 仓库目录; branch: 远端分支名
    @output — Set[hash] | None
    @degraded — origin/<branch> 缺失 (未知) 或 git 失败 -> None
    """
    out = run_git(root, ["rev-list", "origin/%s..HEAD" % branch])
    if out is None:
        return None
    return {line.strip() for line in out.splitlines() if line.strip()}


def git_tags(root: Path) -> List[str]:
    """git tag 列表 (版本倒序); git 失败 -> [] (调用方标'版本待 tag')"""
    out = run_git(root, ["tag", "--sort=-v:refname"])
    if out is None:
        return []
    return [line.strip() for line in out.splitlines() if line.strip()]


# VERSION.md 条目: "## V4.6.2 (2026-08-07) — D317 修复（...）"
_VERSION_HEAD_RE = re.compile(r"^##\s+(V\d+\.\d+\.\d+)\s*\(([^)]*)\)\s*[—-]\s*(.*)$")


def read_version_md(path: Path) -> List[Dict[str, str]]:
    """VERSION.md 条目解析: [{version, date, title}], 文档顺序 (新在前)。

    @input  — path: .codex/control-tower/VERSION.md
    @output — 条目列表; 缺失/不可读 -> []
    """
    if not path.exists():
        return []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return []
    entries: List[Dict[str, str]] = []
    for line in text.splitlines():
        m = _VERSION_HEAD_RE.match(line.strip())
        if m:
            entries.append({"version": m.group(1), "date": m.group(2), "title": m.group(3).strip()})
    return entries


def read_version_log(path: Path) -> List[Dict[str, str]]:
    """version.log JSON 追加流解析: [{version, changes, time}], 新在前。

    @input  — path: .codex/control-tower/logs/version.log
    @output — 条目列表; 缺失/不可读 -> []
    """
    if not path.exists():
        return []
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []
    entries: List[Dict[str, str]] = []
    for line in reversed(lines):
        line = line.strip()
        if not line:
            continue
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        entries.append({
            "version": d.get("version", ""), "changes": d.get("changes", ""),
            "time": d.get("time", ""),
        })
    return entries


_CI_JSON_FIELDS = "workflowName,status,conclusion,headSha,displayTitle,createdAt"


def read_ci(root: Path, branch: str, limit: int = CI_LIMIT, gh_bin: str = "gh",
            runner: Optional[Callable] = None) -> Dict[str, Any]:
    """gh run list 最近 N 次 (branch 过滤): {runs: [...], degraded: str|None}。

    @input  — root: 仓库目录; branch: 分支; limit: 拉取量;
              gh_bin: gh 可执行路径; runner: 测试注入 (默认 subprocess.run)
    @output — {"runs": [run...], "degraded": None|str}
    @degraded — gh 缺失/非零退出/输出不可解析 -> runs=[] + degraded 原因 (不假 0)
    """
    cmd = [gh_bin, "run", "list", "--branch", branch, "--limit", str(limit),
           "--json", _CI_JSON_FIELDS]
    run = runner or subprocess.run
    try:
        r = run(cmd, capture_output=True, text=True, encoding="utf-8",
                errors="replace", timeout=30, cwd=str(root))
    except (OSError, subprocess.TimeoutExpired) as e:
        return {"runs": [], "degraded": "gh 不可用: %s" % e}
    if getattr(r, "returncode", 1) != 0:
        err = (getattr(r, "stderr", "") or "").strip()
        return {"runs": [], "degraded": "gh 不可用" + (": %s" % err[:120] if err else "")}
    try:
        runs = json.loads(getattr(r, "stdout", "") or "[]")
    except json.JSONDecodeError as e:
        return {"runs": [], "degraded": "gh 输出解析失败: %s" % e}
    return {"runs": runs if isinstance(runs, list) else [], "degraded": None}


def read_audit(path: Path) -> Dict[str, Any]:
    """audit-result.json: {"data": dict|None, "degraded": str|None}。

    @input  — path: .codex/audit/audit-result.json
    @output — data 原文 | None; degraded 缺失/损坏原因
    """
    if not path.exists():
        return {"data": None, "degraded": "无审计数据 (audit-result.json 缺失)"}
    try:
        return {"data": json.loads(path.read_text(encoding="utf-8")), "degraded": None}
    except (json.JSONDecodeError, OSError) as e:
        return {"data": None, "degraded": "审计 JSON 损坏: %s" % e}


def parse_override(path: Path) -> Dict[str, Any]:
    """board-override.yaml 手动薄层 (生成器只读, git 无法表达的事实唯一入口)。

    支持 YAML 子集: 注释 (#), 段头 (priorities:/statuses:/blocked:/backlog:/decisions:),
    列表项 (- Dxxx: text | - text)。
    @input  — path: docs/synova/coverage/board-override.yaml
    @output — {priorities: {D#: str}, statuses: {D#: str}, blocked: {D#: str},
               backlog: [str], decisions: [str]}; 文件缺失 -> {}
    """
    if not path.exists():
        return {}
    sections: Dict[str, Any] = {"priorities": {}, "statuses": {}, "blocked": {},
                                "backlog": [], "decisions": []}
    current: Optional[str] = None
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return {}
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([a-zA-Z_]+):\s*$", line)
        if m:
            current = m.group(1) if m.group(1) in sections else None
            continue
        if current and line.startswith("- "):
            item = line[2:].strip()
            dm = re.match(r"^(D\d+)\s*:\s*(.*)$", item, flags=re.IGNORECASE)
            if dm and current in ("priorities", "statuses", "blocked"):
                sections[current][dm.group(1).upper()] = dm.group(2).strip()
            else:
                sections[current].append(item)
    return sections


# dev doc 头部注释: "状态: dev doc | 2026-08-08 | 优先级 P1"
_DOC_STATUS_RE = re.compile(
    r"状态:\s*(.+?)\s*\|\s*(\d{4}-\d{2}-\d{2})\s*\|\s*优先级\s*(P\d)", re.IGNORECASE)


def parse_doc_header(text: str) -> Dict[str, str]:
    """dev doc 头部 HTML 注释解析: -> {status, date, priority}; 无匹配 -> {}。

    @input  — text: 文件内容
    @output — 头字段 dict; 缺失 -> {}
    """
    m = _DOC_STATUS_RE.search(text)
    if not m:
        return {}
    return {"status": m.group(1).strip(), "date": m.group(2), "priority": m.group(3).upper()}


def scan_dev_docs(dev_docs_dir: Path) -> List[Dict[str, Any]]:
    """docs/plans/codex/implementation/*.md 扫描: D#/标题/头状态; 按 D# 倒序。

    @input  — dev_docs_dir: implementation 目录
    @output — [{d_id, title, status, date, priority}]; 目录缺失 -> []
    """
    if not dev_docs_dir.exists():
        return []
    docs: List[Dict[str, Any]] = []
    for f in sorted(dev_docs_dir.glob("*.md")):
        m = re.search(r"(D\d+)", f.name)
        if not m:
            continue
        try:
            text = f.read_text(encoding="utf-8")
        except OSError:
            text = ""
        title = re.sub(r"^SYNOVA-IMPL-\s*", "", f.stem)
        title = re.sub(r"[-_]\d{8}$", "", title)
        info = parse_doc_header(text)
        docs.append({
            "d_id": m.group(1), "title": title,
            "status": info.get("status", ""), "date": info.get("date", ""),
            "priority": info.get("priority", ""),
        })
    docs.sort(key=lambda d: int(re.search(r"\d+", d["d_id"]).group(0)), reverse=True)
    return docs


def scan_briefs(briefs_dir: Path) -> Dict[str, Dict[str, Any]]:
    """.claude/task-briefs/*.md 扫描: {D#: {exists: True, title: 去前缀文件名}}。

    @input  — briefs_dir: task-briefs 目录
    @output — D# -> 元信息; 目录缺失 -> {}
    """
    if not briefs_dir.exists():
        return {}
    found: Dict[str, Dict[str, Any]] = {}
    for f in briefs_dir.glob("*.md"):
        m = re.search(r"(D\d+)", f.name)
        if not m:
            continue
        title = re.sub(r"^D\d+[\s_-]*", "", f.stem)
        found[m.group(1)] = {"exists": True, "title": title}
    return found


def build_tasks(dev_docs: List[Dict[str, Any]], briefs: Dict[str, Dict[str, Any]],
                commits: List[Dict[str, Any]], unpushed: Optional[Set[str]],
                override: Dict[str, Any]) -> List[Dict[str, Any]]:
    """任务并集 (dev docs + git 提交 + override), 每 D# 一行; 按 D# 倒序。

    @input  — dev_docs/briefs/commits/unpushed/override: 各数据源解析结果
    @output — [{d_id, title, status, priority, has_brief, doc, commit, pushed}]
    @degraded — unpushed=None -> pushed=None (未知, 渲染标'未知')
    """
    override = override or {}
    ovr_pri = override.get("priorities", {})
    ovr_status = override.get("statuses", {})
    ovr_blocked = override.get("blocked", {})

    # D# -> 最新提交 (git log 最新在前 -> 首条即最新)
    latest: Dict[str, Dict[str, Any]] = {}
    for c in commits:
        for d in c["d_ids"]:
            if d not in latest:
                latest[d] = c

    # backlog/decisions 中 D#: 标题一并提取 ("D331: git notes 独立任务" -> title)
    ovr_titles: Dict[str, str] = {}
    for item in override.get("backlog", []) + override.get("decisions", []):
        m = re.match(r"^(D\d+)\s*:\s*(.*)$", item, flags=re.IGNORECASE)
        if m:
            ovr_titles[m.group(1).upper()] = m.group(2).strip()

    d_ids = (set(latest) | {d["d_id"] for d in dev_docs}
             | set(ovr_pri) | set(ovr_status) | set(ovr_blocked) | set(ovr_titles))

    tasks: List[Dict[str, Any]] = []
    for d_id in sorted(d_ids,
                       key=lambda s: (int(re.search(r"\d+", s).group(0)), s), reverse=True):
        commit = latest.get(d_id)
        doc = next((d for d in dev_docs if d["d_id"] == d_id), None)
        brief = briefs.get(d_id)

        # 标题: override > dev doc > brief 文件名 > commit subject
        title = (ovr_titles.get(d_id) or ""
                 or (doc["title"] if doc else "")
                 or (brief["title"] if brief else "")
                 or (commit["subject"][:80] if commit else ""))
        title = re.sub(r"^D\d+\s*[-_:：]?\s*", "", title)

        # 状态: override > blocked > dev doc 头 > 派生 (中性 token, 渲染时按语言翻译)
        status = (ovr_status.get(d_id)
                  or ("🔴 blocked: %s" % ovr_blocked[d_id] if d_id in ovr_blocked else "")
                  or (doc["status"] if doc else "")
                  or ("STATE_COMMITTED" if commit else
                      ("STATE_BRIEF" if brief else "STATE_TODO")))
        priority = ovr_pri.get(d_id) or (doc["priority"] if doc else "")

        pushed: Optional[bool] = None
        if commit is not None:
            pushed = commit["hash"] not in unpushed if unpushed is not None else None

        tasks.append({
            "d_id": d_id, "title": title, "status": status, "priority": priority,
            "has_brief": bool(brief), "doc": doc or None, "commit": commit,
            "pushed": pushed,
        })
    return tasks


# ─── 渲染 ─────────────────────────────────────────────────────────────────────

# CI 结论排序: failure 最差 -> success 最好
_CI_ORDER = {"failure": 0, "in_progress": 1, "cancelled": 2, "skipped": 3, "success": 4}
_CI_MARK = {"failure": "❌", "in_progress": "⏳", "cancelled": "➖", "skipped": "➖", "success": "✅"}


def task_ci_marks(tasks: List[Dict[str, Any]], runs: List[Dict[str, Any]]) -> Dict[str, str]:
    """每 D# 的 CI 结论标记: 按最新提交 headSha 匹配 gh run, 多工作流取最差。

    @input  — tasks: build_tasks 输出; runs: read_ci 输出
    @output — {D#: "✅"|"❌"|"⏳"|"➖"|"—"}
    @degraded — 无匹配 run / 无提交 -> "—"
    """
    marks: Dict[str, str] = {}
    for t in tasks:
        c = t.get("commit")
        if not c or not runs:
            marks[t["d_id"]] = "—"
            continue
        matches = [r for r in runs if r.get("headSha") == c["hash"]]
        if not matches:
            marks[t["d_id"]] = "—"
            continue
        worst = min(matches, key=lambda r: _CI_ORDER.get(r.get("conclusion", ""), 5))
        marks[t["d_id"]] = _CI_MARK.get(worst.get("conclusion", ""), "❓")
    return marks


def _pushed_mark(pushed: Optional[bool], ln: Dict[str, str]) -> str:
    """推送状态标记: True ✅ / False ❌ / None 未知 (不假绿不假红)"""
    if pushed is True:
        return ln["pushed_yes"]
    if pushed is False:
        return ln["pushed_no"]
    return ln["unknown"]


def render_auto(tasks: List[Dict[str, Any]], versions: List[Dict[str, str]],
                tags: List[str], ci: Dict[str, Any], audit: Dict[str, Any],
                sync: Tuple[Optional[int], Optional[int]], lang: str,
                vlog: Optional[List[Dict[str, str]]] = None) -> str:
    """渲染 AUTO 区 (含 marker): 任务状态 + 版本历史 + CI + 同步健康。

    @input  — tasks: build_tasks; versions: read_version_md; tags: git_tags;
              ci: read_ci; audit: read_audit; sync: (未推送数, 工作区变更数);
              lang: "cn"|"en"; vlog: read_version_log (可选, 默认无)
    @output — AUTO marker 之间的 Markdown (含 marker 本身)
    @degraded — ci/audit/sync 缺失 -> 段内逐项标注, 不伪造数字
    """
    ln = L10N.get(lang, L10N["cn"])
    parts: List[str] = [AUTO_START, ln["task_status"], ln["task_note"]]

    # ── 任务状态表 (D# | 任务 | 状态 | 提交 | 作者 | 日期 | 推送 | CI | 审计) ──
    ci_runs = ci.get("runs", [])
    marks = task_ci_marks(tasks, ci_runs)
    header = "| D# | %s | %s | %s | %s | %s | %s | %s | %s |" % (
        ln["task"], ln["status"], ln["commit"], ln["author"],
        ln["date"], ln["pushed"], ln["ci"], ln["audit"])
    sep = "|----|-----|------|------|------|------|:---:|:---:|:---:|"
    rows: List[str] = []
    for t in tasks:
        c = t["commit"]
        status_cell = t["status"]
        if status_cell == "STATE_COMMITTED":
            status_cell = ln["state_committed"]
        elif status_cell == "STATE_BRIEF":
            status_cell = ln["state_brief"]
        elif status_cell == "STATE_TODO":
            status_cell = ln["state_todo"]
        if t["priority"]:
            status_cell = "%s（%s）" % (status_cell, t["priority"])
        rows.append("| %s | %s | %s | %s | %s | %s | %s | %s | — |" % (
            t["d_id"],
            _md_cell(t["title"] or "—", 48),
            _md_cell(status_cell or "—", 40),
            c["short_hash"] if c else "—",
            _md_cell(c["author"] if c else "—", 20),
            c["date"] if c else ((t["doc"].get("date") if t["doc"] else None) or "—"),
            _pushed_mark(t["pushed"], ln),
            marks.get(t["d_id"], "—"),
        ))
    if not rows:
        rows.append("| — | %s | — | — | — | — | — | — | — |" % ln["empty_table"])
    parts.extend([header, sep] + rows)

    # 审计全局摘要 + degraded 标注
    if audit.get("data"):
        d = audit["data"]
        note = "%s: P0 %s / P1 %s / P2 %s @ %s" % (
            ln["audit_note"], d.get("p0Count", "?"), d.get("p1Count", "?"),
            d.get("p2Count", "?"), d.get("generatedAt", "?"))
    else:
        note = "%s: degraded: %s" % (ln["audit_note"], audit.get("degraded", "无数据"))
    parts.append("> " + note)

    # ── 版本历史 ──
    parts.append(ln["version_hist"])
    parts.append("> " + ln["version_note"])
    v_header = "| %s | %s | %s | %s |" % (ln["version"], ln["version_date"], ln["changes"], ln["tag"])
    v_sep = "|------|------------|------|:---:|"
    v_rows: List[str] = []
    for v in versions:
        tag_mark = "✅" if v["version"] in tags else "—"
        v_rows.append("| %s | %s | %s | %s |" % (
            v["version"], v["date"], _md_cell(v["title"] or "—", 60), tag_mark))
    if not v_rows:
        v_rows.append("| — | — | %s | — |" % ln["empty_version"])
    parts.extend([v_header, v_sep] + v_rows)
    if not tags:
        parts.append("> ⚠️ %s" % ln["tag_pending"])
    # version.log 最近 3 条 (时间精确, 运行时产物)
    for e in (vlog or [])[:3]:
        parts.append("- %s %s: %s" % (e["version"], e["time"], _md_cell(e["changes"] or "—", 60)))

    # ── CI 状态 ──
    parts.append(ln["ci_status"])
    if ci.get("degraded"):
        parts.append("> degraded: %s" % ci["degraded"])
    c_header = "| %s | %s | %s | %s | %s |" % (ln["run"], ln["workflow"], ln["run_status"],
                                               ln["conclusion"], ln["related_d"])
    c_sep = "|:---:|------|:---:|:---:|------|"
    c_rows: List[str] = []
    for i, r in enumerate(ci_runs, 1):
        d_ids = " ".join(sorted(set(re.findall(r"D\d+", r.get("displayTitle", "")))))
        c_rows.append("| %d | %s | %s | %s %s | %s |" % (
            i, _md_cell(r.get("workflowName", "—"), 30),
            r.get("status", "—"),
            _CI_MARK.get(r.get("conclusion", ""), "❓"), r.get("conclusion", "—"),
            d_ids or "—"))
    if not c_rows:
        c_rows.append("| — | %s | — | — | — |" % ln["empty_run"])
    parts.extend([c_header, c_sep] + c_rows)

    # ── 同步健康 (D323 预留) ──
    parts.append(ln["sync_health"])
    n_unpushed, n_porcelain = sync
    if n_unpushed is None:
        parts.append("- %s: 未知（origin 缺失或 git 失败 — degraded）" % ln["unpushed"])
    else:
        parts.append("- %s: %d（origin/<branch>..HEAD）" % (ln["unpushed"], n_unpushed))
    if n_porcelain is None:
        parts.append("- %s: 未知（git status 失败 — degraded）" % ln["porcelain"])
    else:
        parts.append("- %s: %d 个文件（git status --porcelain）" % (ln["porcelain"], n_porcelain))
    parts.append("> %s" % ln["sync_reserved"])

    parts.append(AUTO_END)
    return "\n".join(parts)


def _md_cell(text: str, max_len: int) -> str:
    """Markdown 单元格清洗: 去换行/管道符, 截断"""
    t = text.replace("|", "／").replace("\n", " ").strip()
    if len(t) > max_len:
        t = t[: max_len - 1] + "…"
    return t


def extract_manual(text: str) -> Optional[str]:
    """提取 MANUAL marker 之间内容 (逐字节, 仅剥 START 后一个换行分隔符)。

    @input  — text: 完整文件内容
    @output — 手动区内容 | None (marker 不完整 -> 首次运行标志)
    @degraded — marker 缺失 -> None (调用方走首次迁移)
    """
    start = text.find(MANUAL_START)
    end = text.find(MANUAL_END)
    if start == -1 or end == -1 or end <= start:
        return None
    inner = text[start + len(MANUAL_START):end]
    if inner.startswith("\n"):
        inner = inner[1:]
    return inner


def strip_auto_section(text: str) -> str:
    """剥离文件中的旧 AUTO 区 (自动区损坏/半迁移时用), 其余原样返回。

    @input  — text: 文件内容
    @output — 移除 AUTO marker 之间内容后的文本
    """
    m = re.search(re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END), text, flags=re.DOTALL)
    if m:
        return text[: m.start()] + text[m.end():]
    return text


def strip_legacy_header(text: str) -> str:
    """首次运行: 剥离旧 frontmatter (---...---) + 首标题 (# ...), 其余原样。

    @input  — text: 无 marker 的旧文件内容
    @output — 待迁入 MANUAL 区的内容 (逐字节保留)
    """
    t = re.sub(r"^---\n.*?\n---\n", "", text, count=1, flags=re.DOTALL)
    t = re.sub(r"^#\s.*\n", "", t, count=1, flags=re.MULTILINE)
    return t


def render_dashboard(auto: str, manual: str, lang: str) -> str:
    """组装完整文件: frontmatter + 标题 + 生成声明 + AUTO 区 + MANUAL 区。

    @input  — auto: render_auto 输出 (含 marker); manual: extract_manual 输出;
              lang: "cn"|"en"
    @output — 完整 Markdown 文件内容
    @degraded — manual 为原始内容时同样逐字节保留
    """
    ln = L10N.get(lang, L10N["cn"])
    header = (
        "---\n"
        "title: \"%s\"\n" % ln["file_title"] +
        "status: \"%s\"\n" % ln["frontmatter_status"] +
        "---\n\n"
        "# %s\n\n" % ln["file_title"] +
        ln["notice"] + "\n"
    )
    # 循环稳定协议: extract_manual 剥 START 后 1 个 \n, 此处对称补回 —
    # 缺失则每次运行 manual 区前导空行被逐次吃掉 (内容漂移, 永不收敛)
    return (
        header
        + auto.rstrip("\n") + "\n"
        + MANUAL_START + "\n" + manual + MANUAL_END + "\n"
    )


def write_if_changed(path: Path, content: str) -> bool:
    """幂等写回: 内容与磁盘一致 -> 不写 (mtime 不变); 不一致 -> 写。

    @input  — path: 目标文件; content: 新内容
    @output — True=已写 / False=未写 (幂等)
    """
    try:
        if path.read_text(encoding="utf-8") == content:
            return False
    except OSError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def sync_health(root: Path, branch: str) -> Tuple[Optional[int], Optional[int]]:
    """同步健康: (未推送提交数, 工作区变更文件数)。

    @input  — root: 仓库目录; branch: 远端分支
    @output — (int|None, int|None); git 失败 -> None (degraded)
    """
    unpushed = git_unpushed(root, branch)
    n_unpushed = len(unpushed) if unpushed is not None else None
    out = run_git(root, ["status", "--porcelain"])
    n_porcelain: Optional[int] = None
    if out is not None:
        # 排除本生成器自己的输出文件 — 否则写文件本身改变计数 →
        # 自动区内容每次运行都不同 → 永远重写 (自引用漂移)
        lines = [l for l in out.splitlines() if l.strip()]
        lines = [l for l in lines if "docs/synova/DASHBOARD" not in l]
        n_porcelain = len(lines)
    return (n_unpushed, n_porcelain)


def render_one(path: Path, tasks: List[Dict[str, Any]], versions: List[Dict[str, str]],
               tags: List[str], ci: Dict[str, Any], audit: Dict[str, Any],
               sync: Tuple[Optional[int], Optional[int]], lang: str,
               vlog: Optional[List[Dict[str, str]]] = None) -> str:
    """单文件渲染: 首次运行旧内容整体迁入 MANUAL 区; 之后 MANUAL 区原样保留。

    @input  — path: DASHBOARD 文件; 其余同 render_auto; vlog: version.log 条目
    @output — 完整文件内容
    @degraded — 文件不可读 -> 手动区为空 (仍渲染 AUTO)
    """
    auto = render_auto(tasks, versions, tags, ci, audit, sync, lang, vlog)
    manual = ""
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except OSError:
            existing = ""
        extracted = extract_manual(existing)
        if extracted is not None:
            manual = extracted
        else:
            # 首次运行 / 手动区损坏: 剥离旧自动区 (若存在), 其余整体迁入手动区
            manual = strip_auto_section(strip_legacy_header(existing))
    return render_dashboard(auto, manual, lang)


def generate(root: Path, branch: str = DEFAULT_BRANCH, gh_bin: str = "gh",
             lang: str = "both", runner: Optional[Callable] = None,
             dry_run: bool = False) -> Dict[str, Any]:
    """编排: 采集 -> 合并 -> 渲染 -> 幂等写回 (CN + EN)。

    @input  — root: 仓库根目录; branch: 分支; gh_bin: gh 路径; lang: cn/en/both;
              runner: CI 测试注入; dry_run: 只算不写
    @output — {written: [路径], unchanged: [路径], degraded: [原因], tasks: n}
    @degraded — 各数据源失败 -> degraded 列表收集 (不阻断渲染)
    """
    dashboard_dir = root / "docs" / "synova"
    dev_docs_dir = root / "docs" / "plans" / "codex" / "implementation"
    briefs_dir = root / ".claude" / "task-briefs"
    version_md = root / ".codex" / "control-tower" / "VERSION.md"
    version_log = root / ".codex" / "control-tower" / "logs" / "version.log"
    audit_path = root / ".codex" / "audit" / "audit-result.json"
    override_path = root / "docs" / "synova" / "coverage" / "board-override.yaml"

    commits = git_log_d(root)
    unpushed = git_unpushed(root, branch)
    dev_docs = scan_dev_docs(dev_docs_dir)
    briefs = scan_briefs(briefs_dir)
    override = parse_override(override_path)
    tasks = build_tasks(dev_docs, briefs, commits, unpushed, override)
    versions = read_version_md(version_md)
    vlog = read_version_log(version_log)
    tags = git_tags(root)
    ci = read_ci(root, branch, CI_LIMIT, gh_bin, runner)
    audit = read_audit(audit_path)
    sync = sync_health(root, branch)

    degraded: List[str] = []
    for name, d in (("CI", ci.get("degraded")), ("审计", audit.get("degraded"))):
        if d:
            degraded.append("%s: %s" % (name, d))
    if unpushed is None:
        degraded.append("推送状态: origin/%s 缺失或 git 失败 — 推送列标'未知'" % branch)

    result: Dict[str, Any] = {"written": [], "unchanged": [], "degraded": degraded,
                              "tasks": len(tasks)}
    for fn, lng in (("DASHBOARD-CN.md", "cn"), ("DASHBOARD.md", "en")):
        if lang != "both" and lang != lng:
            continue
        path = dashboard_dir / fn
        content = render_one(path, tasks, versions, tags, ci, audit, sync, lng, vlog)
        if dry_run:
            result["unchanged"].append(str(path))
            continue
        if write_if_changed(path, content):
            result["written"].append(str(path))
        else:
            result["unchanged"].append(str(path))
    return result


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="仪表盘 git 化生成器 (D320) — 渲染 DASHBOARD-CN/EN 为 git 投影 + 薄手动层")
    parser.add_argument("--lang", choices=["cn", "en", "both"], default="both",
                        help="生成语言 (默认 both)")
    parser.add_argument("--root", default=str(PROJECT_ROOT),
                        help="仓库根目录 (测试注入用)")
    parser.add_argument("--branch", default=DEFAULT_BRANCH, help="主开发分支")
    parser.add_argument("--gh-bin", default="gh", help="gh 可执行路径")
    parser.add_argument("--dry-run", action="store_true", help="只计算不写文件")
    args = parser.parse_args(argv)

    result = generate(Path(args.root), branch=args.branch, gh_bin=args.gh_bin,
                      lang=args.lang, dry_run=args.dry_run)
    for d in result["degraded"]:
        print("[gen-task-board] [WARN] degraded: %s" % d, file=sys.stderr)
    if result["written"]:
        print("[gen-task-board] written: %s" % ", ".join(result["written"]))
    if result["unchanged"]:
        print("[gen-task-board] unchanged (幂等): %d 文件" % len(result["unchanged"]))
    print("[gen-task-board] tasks=%d" % result["tasks"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
