#!/usr/bin/env bash
# ============================================================================
# check-contract-gaps.sh — 契约覆盖缺口扫描 (D25)
#
# 扫描所有 compute 和 sentinel 模块，检查 @contract 覆盖缺口:
#   compute: @input/@output/@degraded JSDoc + 配对测试 + ≥3 expect
#   sentinel: manifest.json + aggregate.ts + 集成测试
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
REPORT_DIR="$REPO_DIR/docs/synova/test-gaps"
REPORT="$REPORT_DIR/D25-gap-report.md"
mkdir -p "$REPORT_DIR"

COMPUTE_DIRS=(
  "$REPO_DIR/extensions/sentinels/shared/computes"
  "$REPO_DIR/extensions/sentinels/unit-economics/computes"
)
SENTINEL_DIR="$REPO_DIR/extensions/sentinels"
TOTAL_COMPUTES=0
TOTAL_SENTINELS=0
GAP_COMPUTES=0
GAP_SENTINELS=0

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  D25 Contract Gap Scan — 契约覆盖缺口扫描"
echo "  $(date '+%Y-%m-%d %H:%M')"
echo "═══════════════════════════════════════════════════════════"

# Build report header
cat > "$REPORT" << 'REPORTHEADER'
# D25 Contract Test Gap Report

> Generated by scripts/ci/check-contract-gaps.sh
> Date:

REPORTHEADER
echo "  $(date '+%Y-%m-%d %H:%M')" >> "$REPORT"
echo "" >> "$REPORT"

echo "" >> "$REPORT"
echo "## Compute Coverage" >> "$REPORT"
echo "" >> "$REPORT"
echo "| File | @input | @output | @degraded | Has Test | ≥3 expect | Status |" >> "$REPORT"
echo "|------|--------|---------|-----------|----------|-----------|--------|" >> "$REPORT"

echo ""
echo "── Scanning Computes ──"
for dir in "${COMPUTE_DIRS[@]}"; do
  [ -d "$dir" ] || continue
  while IFS= read -r file; do
    [ -z "$file" ] && continue
    TOTAL_COMPUTES=$((TOTAL_COMPUTES+1))
    rel="${file#$REPO_DIR/}"

    # Check @input, @output, @degraded
    has_input=0; grep -q '@input' "$file" 2>/dev/null && has_input=1
    has_output=0; grep -q '@output' "$file" 2>/dev/null && has_output=1
    has_degraded=0; grep -q '@degraded' "$file" 2>/dev/null && has_degraded=1

    # Find paired test
    base=$(basename "$file" .ts)
    testfile=$(find "$REPO_DIR/tests" -name "${base}.test.ts" -o -name "${base}*.test.ts" 2>/dev/null | head -1)
    has_test="❌"
    expect_count=0
    if [ -n "$testfile" ]; then
      has_test="✅"
      expect_count=$(grep -c 'expect(' "$testfile" 2>/dev/null || echo 0)
    fi
    expect_ok="❌"
    [ "$expect_count" -ge 3 ] && expect_ok="✅"

    # Overall status
    status="❌"
    [ "$has_input" = "1" ] && [ "$has_output" = "1" ] && [ "$has_degraded" = "1" ] && [ "$has_test" = "✅" ] && [ "$expect_ok" = "✅" ] && status="✅"

    [ "$status" = "❌" ] && GAP_COMPUTES=$((GAP_COMPUTES+1))

    echo "| $rel | $([ "$has_input" = "1" ] && echo "✅" || echo "❌") | $([ "$has_output" = "1" ] && echo "✅" || echo "❌") | $([ "$has_degraded" = "1" ] && echo "✅" || echo "❌") | $has_test | $expect_ok ($expect_count) | $status |" >> "$REPORT"
    echo -n "$([ "$status" = "✅" ] && echo "." || echo "x")"
  done < <(find "$dir" -name '*.ts' -not -name 'index.ts' -not -name '*.test.ts' 2>/dev/null)
done
echo ""
echo ""

echo "## Sentinel Coverage" >> "$REPORT"
echo "" >> "$REPORT"
echo "| Sentinel | Has aggregate.ts | Has integration test | Status |" >> "$REPORT"
echo "|----------|-----------------|---------------------|--------|" >> "$REPORT"

echo "── Scanning Sentinels ──"
for sentinel_dir in "$SENTINEL_DIR"/*/; do
  [ -d "$sentinel_dir" ] || continue
  name=$(basename "$sentinel_dir")
  # Skip _extinct
  [[ "$name" == _* ]] && continue

  TOTAL_SENTINELS=$((TOTAL_SENTINELS+1))

  has_aggregate="❌"
  [ -f "$sentinel_dir/aggregate.ts" ] && has_aggregate="✅"

  has_test="❌"
  testfile=$(find "$REPO_DIR/tests" -path "*${name}*" -name '*.test.ts' 2>/dev/null | head -1)
  [ -n "$testfile" ] && has_test="✅"

  status="❌"
  [ "$has_aggregate" = "✅" ] && [ "$has_test" = "✅" ] && status="✅"
  [ "$status" = "❌" ] && GAP_SENTINELS=$((GAP_SENTINELS+1))

  echo "| $name | $has_aggregate | $has_test | $status |" >> "$REPORT"
  echo -n "$([ "$status" = "✅" ] && echo "." || echo "x")"
done
echo ""

# Summary
{
  echo ""
  echo "## Summary"
  echo ""
  echo "| Metric | Value |"
  echo "|--------|-------|"
  echo "| Total Compute Files | $TOTAL_COMPUTES |"
  echo "| Compute Gaps | $GAP_COMPUTES |"
  echo "| Total Sentinel Dirs | $TOTAL_SENTINELS |"
  echo "| Sentinel Gaps | $GAP_SENTINELS |"
} >> "$REPORT"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Total computes: $TOTAL_COMPUTES | Gaps: $GAP_COMPUTES"
echo "  Total sentinels: $TOTAL_SENTINELS | Gaps: $GAP_SENTINELS"
echo "  Report: $REPORT"
echo "═══════════════════════════════════════════════════════════"
echo ""
exit $((GAP_COMPUTES + GAP_SENTINELS))
