import Database from 'better-sqlite3';
import { mkdirSync, writeFileSync, rmSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
const WT = '/Users/wane/SynovaAgent/.synova-wt-vd968b';
process.chdir(WT);
const FIX = join(tmpdir(), 'vd968-shape'); rmSync(FIX, { recursive: true, force: true });
const dir = join(FIX, 'vd968-only'); mkdirSync(dir, { recursive: true });
writeFileSync(join(dir, 'manifest.json'), JSON.stringify({ name: 'vd968-only', version: '1.0.0', type: 'sentinel', displayName: 'x', description: 'd', schedule: '0 9 * * *', expert: 'fundamental-efficiency', priority: 'P2', computes: [], thresholds: {}, aggregation: 'worst_first', context: { requiredDataSources: [], dataAccess: { allowedDimensions: [], sensitiveAccess: 'read' } }, entryPoint: './aggregate.ts', exportKey: 'vd968FixtureSentinel' }));
writeFileSync(join(dir, 'aggregate.ts'), "export const vd968FixtureSentinel = { async check() { return [{ id: 'vd968-real-finding', severity: 'warning', title: 't', description: 'd', evidence: ['e'], suggestion: 's', detectedAt: new Date().toISOString() }]; } };\n");
process.env.SENTINELS_FIXTURE_DIR = FIX;
const { loadSentinels, clearSentinelCache, registerLoadedSentinels } = await import(`${WT}/src/sentinel/sentinel-loader.ts`);
const { destroySentinelRegistry } = await import(`${WT}/src/sentinel/registry.ts`);
const { reconcileSchema } = await import(`${WT}/src/store/schema-migration.ts`);
const { createSentinelEventsTable } = await import(`${WT}/src/sentinel/sentinel-events.ts`);
const { CronScheduler } = await import(`${WT}/src/cron/scheduler.ts`);
const { SentinelRunner } = await import(`${WT}/src/sentinel/runner.ts`);
clearSentinelCache(); destroySentinelRegistry();
console.log('# load =', loadSentinels().sentinels.length);
console.log('# register =', JSON.stringify(await registerLoadedSentinels()));
const db = new Database(':memory:'); reconcileSchema(db); createSentinelEventsTable(db);
const runner = new SentinelRunner(new CronScheduler(db), db);
const r = await (runner as any).runOnce('sentinel-vd968-only');
console.log('# runOnce 返回 findings =', JSON.stringify((r as any)?.findings?.map((f: any) => f.id)));
const rows = db.prepare('SELECT seq, event_type, sentinel_id, payload FROM sentinel_events ORDER BY seq DESC LIMIT 3').all();
console.log('# 事件行 =', JSON.stringify(rows, null, 1).slice(0, 1200));
db.close(); rmSync(FIX, { recursive: true, force: true }); process.exit(0);
